### ISSUE TITLE
[📚 Epic] `docker compose` commands to deploy on Kubernetes

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#1142]
**Description**
Compose-cli allows to use compose model both on local and ECS or ACI cloud platforms, but one of the most recurring question is "_how about Kubernetes?_".

While there's already a few tools to address this need, we obviously want compose-cli to also support Kubernetes and demonstrate compose-spec can make developer life simpler with a higher level abstraction.

So we will create a kubernetes ⚓️ backend to convert compose 🐙 model into helm ☸️ 

**Implementation**
Compose model will be translated into Helm charts to embrace Kubernetes ecosystem and tools and offer a smooth transition path (like we did for ECS using CloudFormation). We can rely on earlier prototype https://github.com/docker/helm-prototype which is mostly feature-complete for simple scenarios. As a CLI plugin to adopt compose command UX, we should be very close to compose.API defined by compose-cli

- [ ] create a new Kubernetes context type and backend #1145
- [ ] 🤔 address design conflict with kubernetes endpoint in the default context type #1146
- [ ] adjust helm-prototype to adopt `compose.API` https://github.com/docker/helm-prototype/issues/10
- [ ] import helm-prototype as backend implementation (try to preserve git history) #1147
- [ ] import e2e tests #1148
- [ ] documentation

**Comment by jamshid** [comment]
Hopefully compose -> k8s is still on the road map?

**Comment by ndeloof** [comment]
already in progress as https://github.com/docker/compose-cli/tree/main/kube
