### ISSUE TITLE
Docker-compose command compatibility list

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#1283]
Check list of commands and flags, from docker-compose help

- [x]   build              Build or rebuild services
  - [x]   #1360 --build-arg key=val     Set build-time variables for services.
  - [x]   #1440 --compress              Compress the build context using gzip
  - [x]   #1440 --force-rm              Always remove intermediate containers.
  - [x]   #1468 -m, --memory MEM        Set memory limit for the build container. - not yet supported in buildkit
  - [x]   #1468 --no-cache              Do not use cache when building the image.
  - [x]   #1468 --no-rm                 Do not remove intermediate containers after a successful build.
  - [x]  #1440 --parallel              Build images in parallel.
  - [x]  #1358 --progress string       Set type of progress output (auto, plain, tty).
  - [x]  #1359 --pull                  Always attempt to pull a newer version of the image.
  - [x] #1280  -q, --quiet             Don't print anything to STDOUT

- [x]   config             Validate and view the Compose file
  - [x] #1286  --resolve-image-digests  Pin image tags to digests.
  - [x]   --no-interpolate         Don't interpolate environment variables.
  - [x] #1280  -q, --quiet              Only validate the configuration, don't print anything.
  - [x]   --services               Print the service names, one per line.
  - [x]   --volumes                Print the volume names, one per line.
  - [x]   --hash="*"               Print the service config hash, one per line.
  - [x]  --profiles does not exist yet in docker-compose but has been requested
- [x]   create             Create services
  - [x]  #1277 --force-recreate       Recreate containers even if their configuration and image haven't changed. Incompatible with --no-recreate.
  - [x] #1277  --no-recreate          If containers already exist, don't recreate them. Incompatible with --force-recreate.
  - [x] #1291  --no-build             Don't build an image, even if it's missing.
  - [x] #1292  --build                Build images before creating containers.

- [x]   down               Stop and remove resources
  - [x] #1269 --rmi type              Remove images. 
  - [x] #1268  -v, --volumes           Remove named volumes declared in the `volumes` section of the Compose file and anonymous volumes attached to containers.
  - [x]  --remove-orphans        Remove containers for services not defined in the Compose file
  - [x] #1275 -t, --timeout TIMEOUT   Specify a shutdown timeout in seconds.
- [x]  #1396 events             Receive real time events from containers.
  - [x]  --json      Output events as a stream of json objects

- [x] #1266  exec               Execute a command in a running container
  - [x]  -d, --detach      Detached mode: Run command in the background.
  - [x]  --privileged      Give extended privileges to the process.
  - [x]  -u, --user USER   Run the command as this user.
  - [x]  -T                Disable pseudo-tty allocation. By default `docker-compose exec` allocates a TTY.
  - [x]  --index=index     index of the container if there are multiple instances of a service [default: 1]
  - [x]  -e, --env KEY=VAL Set environment variables (can be used multiple times not supported in API < 1.25)
  - [x]  -w, --workdir DIR Path to workdir directory for this command.

- [x]  help               Get help on a command

- [x]  images             List images.
   - [x] -q, --quiet  Only display IDs

- [x]  kill               Kill containers
  - [x]  -s SIGNAL         SIGNAL to send to the container. Default signal is SIGKILL.

- [x]  logs               View output from containers
  - [x]  #1270 --no-color              Produce monochrome output.
  - [x] #1060 -f, --follow            Follow log output.
  - [x] #1272 -t, --timestamps        Show timestamps.
  - [x]  --tail="all"            Number of lines to show from the end of the log for each container.
  - [x] #1271 --no-log-prefix         Don't print prefix in logs.

- [x]  pause              Pause services

- [x]  #1439 port               Print the public port for a port binding
  - [x]  --protocol=proto  tcp or udp [default: tcp]
  - [x]  --index=index     index of the container if there are multiple instances of a service [default: 1]

- [x]  ps                 List containers
  - [x]  -q, --quiet          Only display IDs
  - [x] #1273 --services           Display services
  - [ ]  ~~--filter KEY=VAL     Filter services by a property~~
  - [x]  -a, --all            Show all stopped containers (including those created by the run command)

- [x]  pull               Pull service images
  - [x] #1276 --ignore-pull-failures  Pull what it can and ignores images with pull failures.
  - [x]  --parallel              Deprecated, pull multiple images in parallel (enabled by default).
  - [x]  --no-parallel           Disable parallel pulling.
  - [x] #1280 -q, --quiet             Pull without printing progress information
  - [x]  #1361 --include-deps          Also pull services declared as dependencies

- [x]  push               Push service images
  - [x] #1276 --ignore-push-failures  Push what it can and ignores images with push failures.

- [x] #1389 restart            Restart services
  - [x] -t, --timeout TIMEOUT      Specify a shutdown timeout in seconds. (default: 10)

- [x]  #1299 rm                 Remove stopped containers
  - [x]  -f, --force   Don't ask to confirm removal
  - [x]  -s, --stop    Stop the containers, if required, before removing
  - [x]  -v            Remove any anonymous volumes attached to containers
  - [ ]  ~~-a, --all     Deprecated - no effect.~~

- [x]  run                Run a one-off command
  - [x]  -d, --detach          Detached mode: Run container in the background, print new container name.
  - [x]  --name NAME           Assign a name to the container
  - [x]  --entrypoint CMD      Override the entrypoint of the image.
  - [x]  -e KEY=VAL            Set an environment variable (can be used multiple times)
  - [x]  -l, --label KEY=VAL   Add or override a label (can be used multiple times)
  - [x]  -u, --user=""         Run as specified username or uid
  - [x]  #1362 --no-deps             Don't start linked services.
  - [x]  --rm                  Remove container after run. Ignored in detached mode.
  - [x]  #1363 -p, --publish=[]      Publish a container's port(s) to the host
  - [x]  --service-ports       Run command with the service's ports enabled and mapped to the host.
  - [x]  #1364 --use-aliases         Use the service's network aliases in the network(s) the container connects to.
  - [x]  #1365 -v, --volume=[]       Bind mount a volume (default [])
  - [x]  -T                    Disable pseudo-tty allocation. By default `docker-compose run` allocates a TTY.
  - [x]  -w, --workdir=""      Working directory inside the container

- [ ]  ~~scale              Set number of containers for a service~~ deprecated
  - [ ] -t, --timeout TIMEOUT      Specify a shutdown timeout in seconds. (default: 10)

- [x]  start              Start services

- [x]  stop               Stop services
  - [x] -t, --timeout TIMEOUT      Specify a shutdown timeout in seconds. (default: 10)

- [x] #1367 top                Display the running processes

- [x]  unpause            Unpause services

- [x]  up                 Create and start containers
  - [x]  -d, --detach               Detached mode: Run containers in the background, print new container names. Incompatible with --abort-on-container-exit.
  - [x]  --no-color                 Produce monochrome output.
  - [x]  #1368 --quiet-pull               Pull without printing progress information
  - [x]  #1369 --no-deps                  Don't start linked services.
  - [x]  --force-recreate           Recreate containers even if their configuration and image haven't changed.
  - [x]  #1370 --always-recreate-deps     Recreate dependent containers. Incompatible with --no-recreate.
  - [x]  --no-recreate              If containers already exist, don't recreate them. Incompatible with --force-recreate and -V.
  - [x] #1291 --no-build                 Don't build an image, even if it's missing.
  - [x]  --no-start                 Don't start the services after creating them.
  - [x]  --build                    Build images before starting containers.
  - [x]  --abort-on-container-exit  Stops all containers if any container was stopped. Incompatible with -d.
  - [x]  #1371 --attach-dependencies      Attach to dependent containers.
  - [x]  #1372 -t, --timeout TIMEOUT      Use this timeout in seconds for container shutdown when attached or when containers are
 already running. (default: 10)
  - [x] #1373 -V, --renew-anon-volumes   Recreate anonymous volumes instead of retrieving data from the previous containers.
  - [x]  --remove-orphans           Remove containers for services not defined in the Compose file.
  - [x]  --exit-code-from SERVICE   Return the exit code of the selected service container. Implies --abort-on-container-exit.
  - [x]  #1287 --scale SERVICE=NUM        Scale SERVICE to NUM instances. Overrides the `scale` setting in the Compose file if present.
  - [x]  --no-log-prefix            Don't print prefix in logs.

- [x]  ~~version            Show version information and quit~~
  - [x]  ~~--short     Shows only Compose's version number.~~

## Common options: 
- [x]  -f, --file FILE             Specify an alternate compose file (default: docker-compose.yml)
- [x]  -p, --project-name NAME     Specify an alternate project name (default: directory name)
- [x]  --profile NAME              Specify a profile to enable
- [x]  ~~-c, --context NAME          Specify a context name~~ at Docker cli root level
- [ ]  --verbose                   Show more output
- [x]  --log-level LEVEL           Set log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
- [x]  --ansi (never|always|auto)  Control when to print ANSI control characters  Wait for users request, this might not be that useful
- [x]  --no-ansi                   Do not print ANSI control characters (DEPRECATED) Wait for users request, this might not be that useful
- [x]  ~~-v, --version               Print version and exit~~ at Docker cli root level
- [x] #1293  -H, --host HOST             Daemon socket to connect to
- [x] #1293  --tls                       Use TLS; implied by --tlsverify
- [x] #1293  --tlscacert CA_PATH         Trust certs signed only by this CA
- [x] #1293  --tlscert CLIENT_CERT_PATH  Path to TLS certificate file
- [x] #1293  --tlskey TLS_KEY_PATH       Path to TLS key file
- [x] #1293  --tlsverify                 Use TLS and verify the remote
- [x] #1293  --skip-hostname-check       Don't check the daemon's hostname against the name specified in the client certificate
- [x] #1279 --project-directory PATH    Specify an alternate working directory (default: the path of the Compose file)
- [x]  ~~--compatibility             If set, Compose will attempt to convert keys in v3 files to their non-Swarm equivalent (DEPRECATED)~~
- [x]  --env-file PATH             Specify an alternate environment file

**Comment by BretFisher** [comment]
I recommend this issue be pinned!

**Comment by ndeloof** [comment]
all commands and flags (but --verbose, not applicable) are now supported, so closing
